services:
  postgres:
    container_name: nestjs-kysely-postgres
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    networks:
      - app-network
    env_file:
      - docker.env
    volumes:
      - ./init-multiple-dbs.sh:/docker-entrypoint-initdb.d/init-multiple-dbs.sh
 
  pgadmin:
    container_name: nestjs-kysely-pgadmin
    image: dpage/pgadmin4
    networks:
      - app-network
    ports:
      - "8080:80"
    env_file:
      - docker.env

  rabbitmq:
    container_name: finance-manager-rabbitmq
    image: rabbitmq:3-management
    ports:
      - "5672:5672"  # AMQP protocol port
      - "15672:15672"  # Management UI port
    networks:
      - app-network
    env_file:
      - docker.env
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
 
networks:
  app-network:
    driver: bridge

volumes:
  rabbitmq_data:
