services:
  postgres:
    container_name: nestjs-kysely-postgres
    image: postgres:17-alpine
    ports:
      - "5433:5432"
    networks:
      - postgres
    env_file:
      - docker.env
 
  pgadmin:
    container_name: nestjs-kysely-pgadmin
    image: dpage/pgadmin4
    networks:
      - postgres
    ports:
      - "8080:80"
    env_file:
      - docker.env
 
networks:
  postgres:
    driver: bridge
