import { AggregateRoot } from '@nestjs/cqrs';
import { AccountType } from '../../../../shared-kernel/core/types/db';
import { AccountCreatedEvent } from '../events/account-created.event';
import { AccountUpdatedEvent } from '../events/account-updated.event';
import { AccountRemovedEvent } from '../events/account-removed.event';

export class AccountAggregate extends AggregateRoot {
  private _id: string;
  private _name: string;
  private _accountType: AccountType;
  private _currency: string;
  private _userId: string;
  private _description?: string;
  private _notes?: string;
  private _icon?: string;
  private _color?: string;
  private _initialBalance: number;
  private _isActive: boolean;
  private _lastReconciled?: Date;
  private _createdAt: Date;
  private _updatedAt: Date;

  // Getters
  get id(): string {
    return this._id;
  }

  get name(): string {
    return this._name;
  }

  get accountType(): AccountType {
    return this._accountType;
  }

  get currency(): string {
    return this._currency;
  }

  get userId(): string {
    return this._userId;
  }

  get description(): string | undefined {
    return this._description;
  }

  get notes(): string | undefined {
    return this._notes;
  }

  get icon(): string | undefined {
    return this._icon;
  }

  get color(): string | undefined {
    return this._color;
  }

  get initialBalance(): number {
    return this._initialBalance;
  }

  get isActive(): boolean {
    return this._isActive;
  }

  get lastReconciled(): Date | undefined {
    return this._lastReconciled;
  }

  get createdAt(): Date {
    return this._createdAt;
  }

  get updatedAt(): Date {
    return this._updatedAt;
  }

  /**
   * Creates a new account
   * @param id - Account ID (should be generated by the system)
   * @param name - Account name
   * @param accountType - Type of account (BANK, CASH, etc.)
   * @param currency - Currency code
   * @param userId - ID of the user who owns the account
   * @param description - Optional description
   * @param notes - Optional notes
   * @param icon - Optional icon
   * @param color - Optional color
   */
  create(
    id: string,
    name: string,
    accountType: AccountType,
    currency: string,
    userId: string,
    description?: string,
    notes?: string,
    icon?: string,
    color?: string,
  ): void {
    // Apply business rules
    this.validateAccountName(name);
    this.validateCurrency(currency);

    // Set properties through event
    this.apply(new AccountCreatedEvent(id, userId));

    // Set initial state
    this._id = id;
    this._name = name;
    this._accountType = accountType;
    this._currency = currency;
    this._userId = userId;
    this._description = description;
    this._notes = notes;
    this._icon = icon;
    this._color = color;
    this._initialBalance = 0;
    this._isActive = true;
    this._createdAt = new Date();
    this._updatedAt = new Date();
  }

  /**
   * Updates account properties
   * @param data - Partial account data to update
   */
  update(data: {
    name?: string;
    description?: string;
    icon?: string;
    color?: string;
  }): void {
    // Apply business rules
    if (data.name !== undefined) {
      this.validateAccountName(data.name);
    }

    // Check if account is active
    if (!this._isActive) {
      throw new Error('Cannot update inactive account');
    }

    // Apply event with changes
    this.apply(
      new AccountUpdatedEvent(
        this._id,
        this._userId,
        data.name,
        this._accountType,
        this._initialBalance,
      ),
    );

    // Update properties
    if (data.name !== undefined) {
      this._name = data.name;
    }
    if (data.description !== undefined) {
      this._description = data.description;
    }
    if (data.icon !== undefined) {
      this._icon = data.icon;
    }
    if (data.color !== undefined) {
      this._color = data.color;
    }
    this._updatedAt = new Date();
  }

  /**
   * Marks account as removed (soft delete by setting isActive to false)
   */
  remove(): void {
    // Check if already inactive
    if (!this._isActive) {
      throw new Error('Account is already removed');
    }

    // Apply event
    this.apply(new AccountRemovedEvent(this._id, this._userId));

    // Update state
    this._isActive = false;
    this._updatedAt = new Date();
  }

  /**
   * Loads the aggregate state from persistence
   * This method is used to reconstitute the aggregate from stored data
   * Note: This is different from AggregateRoot's loadFromHistory which is for event sourcing
   * @param accountData - Account data from the database
   */
  loadState(accountData: {
    id: string;
    name: string;
    accountType: AccountType;
    currency: string;
    userId: string;
    description?: string | null;
    notes?: string | null;
    icon?: string | null;
    color?: string | null;
    initialBalance: number | string;
    isActive: boolean;
    lastReconciled?: Date | null;
    createdAt: Date;
    updatedAt: Date;
  }): void {
    this._id = accountData.id;
    this._name = accountData.name;
    this._accountType = accountData.accountType;
    this._currency = accountData.currency;
    this._userId = accountData.userId;
    this._description = accountData.description ?? undefined;
    this._notes = accountData.notes ?? undefined;
    this._icon = accountData.icon ?? undefined;
    this._color = accountData.color ?? undefined;
    this._initialBalance =
      typeof accountData.initialBalance === 'string'
        ? parseFloat(accountData.initialBalance)
        : accountData.initialBalance;
    this._isActive = accountData.isActive;
    this._lastReconciled = accountData.lastReconciled ?? undefined;
    this._createdAt = accountData.createdAt;
    this._updatedAt = accountData.updatedAt;
  }

  // Business rule validators
  private validateAccountName(name: string): void {
    if (!name || name.trim().length === 0) {
      throw new Error('Account name cannot be empty');
    }
    if (name.length > 100) {
      throw new Error('Account name cannot exceed 100 characters');
    }
  }

  private validateCurrency(currency: string): void {
    if (!currency || currency.trim().length === 0) {
      throw new Error('Currency cannot be empty');
    }
    // Basic currency code validation (ISO 4217 is 3 characters)
    if (currency.length !== 3) {
      throw new Error('Currency code must be 3 characters');
    }
  }

  // Event handlers (these are called when events are applied via loadFromHistory)
  // In a full event sourcing implementation, these would reconstruct state from events
  private onAccountCreatedEvent(event: AccountCreatedEvent): void {
    // State is set in create() method
    // In full event sourcing, this would be the only place state is set
  }

  private onAccountUpdatedEvent(event: AccountUpdatedEvent): void {
    // State is updated in update() method
    // In full event sourcing, this would be the only place state is updated
  }

  private onAccountRemovedEvent(event: AccountRemovedEvent): void {
    // State is updated in remove() method
    // In full event sourcing, this would be the only place state is updated
  }
}
