/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely';

export type AccountType =
  | 'ASSET'
  | 'BANK'
  | 'CASH'
  | 'CREDIT'
  | 'INVESTMENT'
  | 'LIABILITY';

export type ArrayType<T> =
  ArrayTypeImpl<T> extends (infer U)[] ? U[] : ArrayTypeImpl<T>;

export type ArrayTypeImpl<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S[], I[], U[]>
    : T[];

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type UserRole = 'admin' | 'user';

export interface Accounts {
  accountType: AccountType;
  color: string | null;
  createdAt: Generated<Timestamp>;
  currency: Generated<string>;
  description: string | null;
  icon: string | null;
  id: string;
  initialBalance: Generated<Numeric>;
  isActive: Generated<boolean>;
  lastReconciled: Timestamp | null;
  name: string;
  transactionIds: Generated<Json>;
  updatedAt: Generated<Timestamp>;
  userId: string;
}

export interface Users {
  createdAt: Generated<Timestamp>;
  email: string;
  id: string;
  name: string;
  password: string;
  roles: Generated<ArrayType<UserRole>>;
  updatedAt: Generated<Timestamp>;
}

export interface DB {
  accounts: Accounts;
  users: Users;
}
