/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type {ColumnType} from 'kysely';

export type AccountType =
  | 'ASSET'
  | 'BANK'
  | 'CASH'
  | 'CREDIT'
  | 'INVESTMENT'
  | 'LIABILITY';

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Role = 'admin' | 'user';

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Accounts {
  accountType: AccountType;
  color: string | null;
  createdAt: Generated<Timestamp>;
  currency: string;
  description: string;
  icon: string | null;
  id: string;
  initialBalance: Numeric;
  isActive: Generated<boolean>;
  lastReconciled: Timestamp;
  name: string;
  updatedAt: Generated<Timestamp>;
  userId: string;
}

export interface Users {
  createdAt: Generated<Timestamp>;
  email: string;
  id: string;
  name: string;
  password: string;
  role: Role;
  updatedAt: Generated<Timestamp>;
}

export interface DB {
  accounts: Accounts;
  users: Users;
}
