/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely';

export type AccountType =
  | 'ASSET'
  | 'BANK'
  | 'CASH'
  | 'CREDIT'
  | 'INVESTMENT'
  | 'LIABILITY';

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type UserRole = 'admin' | 'user';

export interface Accounts {
  account_type: AccountType;
  color: string | null;
  created_at: Generated<Timestamp>;
  currency: Generated<string>;
  description: string | null;
  icon: string | null;
  id: string;
  initial_balance: Generated<Numeric>;
  is_active: Generated<boolean>;
  last_reconciled: Timestamp | null;
  name: string;
  transaction_ids: Generated<Json>;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface Users {
  created_at: Generated<Timestamp>;
  email: string;
  id: string;
  name: string;
  password: string;
  updated_at: Generated<Timestamp>;
}

export interface UsersRoles {
  role: UserRole;
  user_id: string;
}

export interface DB {
  accounts: Accounts;
  users: Users;
  users_roles: UsersRoles;
}
