services:
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - microservices-network
    env_file:
      - .env

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"  # AMQP protocol port
      - "15672:15672"  # Management UI port
    networks:
      - microservices-network
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbitmq_gateway_data:/var/lib/rabbitmq

networks:
  microservices-network:
    driver: bridge

volumes:
  rabbitmq_gateway_data:
